/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Component Pack 5
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <DataLine_aliases.h>
#include <DataLine.h>
#include <ClockLine_aliases.h>
#include <ClockLine.h>
#include <FREX_aliases.h>
#include <FREX.h>
#include <EXPST_aliases.h>
#include <EXPST.h>
#include <XCLK_aliases.h>
#include <XCLK.h>
#include <PWND_aliases.h>
#include <PWND.h>
#include <RST_B_aliases.h>
#include <RST_B.h>
#include <Clock_1.h>
#include <LCD_Char_1.h>
#include <DataBus_aliases.h>
#include <DataBus.h>
#include <PCLK_aliases.h>
#include <PCLK.h>
#include <VREF_aliases.h>
#include <VREF.h>
#include <HREF_aliases.h>
#include <HREF.h>
#include <isr_PCLK.h>
#include <isr_VREF.h>
#include <isr_HREF.h>
#include <LED_aliases.h>
#include <LED.h>
#include <isr_HREF_LOW.h>
#include <UART.h>
#include <isr_tx.h>
#include <isr_rx.h>
#include <LCD_Char_1_LCDPort_aliases.h>
#include <LCD_Char_1_LCDPort.h>
#include <UART_IntClock.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/
